export const planetsList = [
  "Sun",
  "Earth",
  "Mars",
  "Saturn",
  "Mercury",
  "Jupiter",
  "Uranus",
  "Neptune",
  "Venus",
];

export const planetsInfo = [
  {
    id: 0,
    name: "Sun",
    size: 1000,
    position: 0,
    orbit_rotation_speed: 0,
    self_rotation_speed: 0.01,
    texture_url: "sun.jpg",
  },
  {
    id: 1,
    name: "Mercury",
    size: 4,
    position: 4000,
    orbit_rotation_speed: 0.07,
    self_rotation_speed: 0.01,
    texture_url: "mercury.jpg",
  },
  {
    id: 2,
    name: "Venus",
    size: 8,
    position: 7000,
    orbit_rotation_speed: 0.06,
    self_rotation_speed: 0.01,
    texture_url: "venus.jpg",
  },
  {
    id: 3,
    name: "Earth",
    size: 10,
    position: 10000,
    orbit_rotation_speed: 0.1,
    self_rotation_speed: 0.01,
    texture_url: "earth.jpg",
  },
  {
    id: 4,
    name: "Mars",
    size: 5,
    position: 15000,
    orbit_rotation_speed: 0.05,
    self_rotation_speed: 0.01,
    texture_url: "mars.jpg",
  },
  {
    id: 5,
    name: "Jupiter",
    size: 100,
    position: 52000,
    orbit_rotation_speed: 0.05,
    self_rotation_speed: 0.01,
    texture_url: "jupiter.jpg",
  },
  {
    id: 6,
    name: "Saturn",
    size: 80,
    position: 95000,
    orbit_rotation_speed: 0.05,
    self_rotation_speed: 0.01,
    texture_url: "saturn.jpg",
  },
  {
    id: 7,
    name: "Uranus",
    size: 40,
    position: 192000,
    orbit_rotation_speed: 0.02,
    self_rotation_speed: 0.01,
    texture_url: "uranus.jpg",
  },
  {
    id: 8,
    name: "Neptune",
    size: 40,
    position: 300000,
    orbit_rotation_speed: 0.03,
    self_rotation_speed: 0.01,
    texture_url: "neptune.jpg",
  },
];
